full_rebuild: true
name: DLF Metadata Assessment Working Group
author: DLF AIG Metadata Working Group
version: V 1.0
encoding: utf-8
baseurl: ""
defaults:
  - scope:
      type: review
    values:
      layout: page
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
collections:
  review:
    output: true
    permalink: /review/:path/
sass:
  sass_dir: _sass
  style: :compressed
exclude: [
.git,
.gitignore,
README.md,
.sass-cache,
config.ru,
vendor,
Gemfile,
Gemfile.lock
]
